### ISSUE TITLE
Set up 

### ISSUE THREAD

**Issue by Sharonina** [4cornerslatam/4Corners-client#1]
- Create set up for the project

- [x]  Vitest
- [x] React
- [x] Typescript
- [x] Sass

**Comment by beresdev** [comment]
"react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.11.2"    

    dev:
    "sass": "^1.62.1",
    "typescript": "^5.0.2",
    "vite": "^4.3.9",
    "vitest": "^0.31.2"

**index.scss** - style initialization

### vitest: 

- script: test ( `npm test` )
