### ISSUE TITLE
Footer-UI, Implementation

### ISSUE THREAD

**Issue by Sharonina** [4cornerslatam/4Corners-client#11]
**Mobile**
> Taking into account the following design, which must be responsive in order to switch to the desktop view:

![Captura de pantalla 2023-06-01 085925](https://github.com/4cornerslatam/4Corners-client/assets/11237463/786a0e9a-9937-40aa-ad7e-c1603b118c5b)

> We need to create the corresponding component for the footer, considering that it will only contain the following content (without watermark):

![Captura de pantalla 2023-06-01 115159](https://github.com/4cornerslatam/4Corners-client/assets/11237463/99a0a53a-bac8-4f2e-acbc-832f26ab163d)

> It should be taken into account that the footer in the hamburger menu has a different appearance, that is:

![Captura de pantalla 2023-06-01 115236](https://github.com/4cornerslatam/4Corners-client/assets/11237463/7dcc9320-a7c3-4436-b2cf-4af733208c1a)

![Captura de pantalla 2023-06-01 115209](https://github.com/4cornerslatam/4Corners-client/assets/11237463/96892aa6-0a14-4716-b8c4-cd17c3b60d8b)

**Desktop**

> Taking into account the previous design, we will now work on the design based on the size of a desktop computer:

![Captura de pantalla 2023-06-01 084225](https://github.com/4cornerslatam/4Corners-client/assets/11237463/78df17b1-22fa-463a-8570-88d30aa00206)

> Please note that our focus is only on this area:

![Captura de pantalla 2023-06-01 115123](https://github.com/4cornerslatam/4Corners-client/assets/11237463/97fbfd10-2876-4b29-b5b3-5e7bb7d7fc49)

**Considerations**
> Take into account the architecture that @beresdev has included in the project
> Make use of CSS variables (in case any color doesn't match, please update it)
> Use iconography in .svg format to reuse icons by modifying only their fill, here is a [recomendation](https://fontawesome.com/)
> Consider the style guidelines included in the [figma](https://www.figma.com/file/KSBDfVKqW5dOcnwsV9EVAL/Untitled?type=design&node-id=0-1&t=95JWD9ZuPzqMeryr-0)

**Comment by beresdev** [comment]
I assign myself this issue, I was already considering it in the ticket I'm working on.
