### ISSUE TITLE
Contact view for mobile

### ISSUE THREAD

**Issue by Sharonina** [4cornerslatam/4Corners-client#19]
Hello @KamilaOjeda, in production we have encountered a roadblock in the design. We need your help to create the 'Contacto' view for the mobile version, as we currently only have the desktop view.

>This is the view we currently have:

<img width="525" alt="Captura de pantalla 2023-06-05 074255" src="https://github.com/4cornerslatam/4Corners-client/assets/11237463/de89cd9e-03b9-47f3-9b17-fb9f909313c3">

**Comment by KamilaOjeda** [comment]
Of course, I'll get to work on it now.

**Comment by KamilaOjeda** [comment]
Please confirm if you can see the current changes:

![Image](https://github.com/4cornerslatam/4Corners-client/assets/116526220/31c77dc5-c632-452e-ab3f-089f594f2d85)

**Comment by Sharonina** [comment]
I confirm receipt, thank you very much <3
