### ISSUE TITLE
Servicios - UI, Implementation

### ISSUE THREAD

**Issue by Sharonina** [4cornerslatam/4Corners-client#21]
**Mobile**
> Taking into account the following design, which must be responsive in order to switch to the desktop view:

<img width="239" alt="Captura de pantalla 2023-06-05 074432" src="https://github.com/4cornerslatam/4Corners-client/assets/11237463/9db6c89a-96c4-423c-9322-27c3f7938e55">

> We need to create the corresponding component for the 'Servicios' view, considering that it will only contain the following content:

<img width="237" alt="Captura de pantalla 2023-06-05 074444" src="https://github.com/4cornerslatam/4Corners-client/assets/11237463/ce5ed871-08fa-4ce7-b195-afafad5dc058">

> Please note that this view receives a card component, which will contain the following information about our services:
>>_**THIS COMPONENT WILL BE CREATED AT ANOTHER TIME**, but it is part of your tasks to generate the behaviour of these cards_

<img width="235" alt="Captura de pantalla 2023-06-05 100418" src="https://github.com/4cornerslatam/4Corners-client/assets/11237463/2d9f8816-626e-4e1e-8e28-3b25160ee832">

**Desktop**

> Taking into account the previous design, we will now work on the design based on the size of a desktop computer, _Please note that our focus is only on this area:_

<img width="525" alt="Captura de pantalla 2023-06-05 074345" src="https://github.com/4cornerslatam/4Corners-client/assets/11237463/51234a6e-570b-430a-8595-af4c5959a549">

>_**REMEMBER: THE CARD COMPONENT WILL BE CREATED AT ANOTHER TIME**, but it is part of your tasks to generate the behaviour of these cards_**

**Considerations**
> Take into account the architecture that @beresdev has included in the project
> Make use of CSS variables (in case any color doesn't match, please update it).
> Consider the style guidelines included in the [figma](https://www.figma.com/file/KSBDfVKqW5dOcnwsV9EVAL/Untitled?type=design&node-id=0-1&t=95JWD9ZuPzqMeryr-0)

**Comment by beresdev** [comment]
## Hover and active behaviour mobile:

https://reactjsexample.com/3d-cover-flow-in-react/

## Hover and active behaviour desktop:

![image](https://github.com/4cornerslatam/4Corners-client/assets/73813833/e8a751f0-a94d-4e31-b084-4b0a46bb371f)
