### ISSUE TITLE
Header - UI, Implementation

### ISSUE THREAD

**Issue by Sharonina** [4cornerslatam/4Corners-client#4]
**Mobile**

> We have this architecture to build for the mobile view, where we have a hamburger menu and the logo.

![Captura de pantalla 2023-05-31 110119](https://github.com/4cornerslatam/4Corners-client/assets/11237463/21f5744c-417b-437e-b142-81624998af0c)

> From this menu, we have the following behavior:

![Captura de pantalla 2023-05-31 110200](https://github.com/4cornerslatam/4Corners-client/assets/11237463/eca91b00-2f67-4dd1-ac97-92cc88be7f6f)

> It shows us a new view with the predefined navigation options, and at the bottom, we have buttons with the corresponding social media logos.

> The hamburger menu should be able to open and close this view.

**Desktop**

> Considering that we start from the mobile development, the design should be responsive and transition to a layout specifically created for computers.
> Our header would no longer have the hamburger menu but a navigation bar like the following:

![Captura de pantalla 2023-05-31 111951](https://github.com/4cornerslatam/4Corners-client/assets/11237463/99615e26-2a79-4d77-99f8-ac45528cbf3f)

> Take into account that when hovering over each navigation option or when it is selected, its color should change and a line should be displayed at the bottom to indicate to the user where they are:

![Captura de pantalla 2023-05-31 113343](https://github.com/4cornerslatam/4Corners-client/assets/11237463/e6a66052-df8c-4c67-9485-a19b2c19481b)

**Considerations:**

> Take into account the previously proposed page names.
> Create a file with possible variable usage:

>> Fonts: Poppins (primary), Roboto (secondary)
>> Colors: #3743AA, #DE5590, #333333, #FFFFFF

**Comment by beresdev** [comment]
It was used a library for hamburger menu icon

https://hamburger-react.netlify.app/
